### ISSUE TITLE
Textual properties available?

### ISSUE THREAD

**Issue by weixincazn** [snap-stanford/stark#5]
As shown in Figure 3, there would be some **textual properties** for each node, such as _"push-along tricycle"_ and _"fun and safe for kids"_. And I wonder if we could see these textual properties in the repo?
— So far, what I've found is the **complete information** for each node with the format like:
{'product': ['title',
  'dimensions',
  'weight',
  'description',
  'features',
  'reviews',
  'Q&A'],
 'brand': ['brand_name']}
 , rather some **phrase-like textual properties** as shown in Figure 3.

**Comment by Wuyxin** [comment]
Hi,

The textual properties are extracted during the generation process of each query, which origins from the complete information. Therefore the textual properties only present partial information. 

Since the textual properties are essentially metadata used to construct the queries, we don't plan to release them considering potential answer leakage. 

Please let me know if this makes sense!

Shirley
